### PR TITLE
Give access to the raw JWT in the user provider (alternative implem)

### PR DESCRIPTION
**Pull request by dunglas**
### Changes

Alternative to #96 (same rationale). This implementation is less intrusive.
Always populate the `token` property of the JWT object.

### References

#96.

### Testing

Please describe how this can be tested by reviewers. Be specific about anything not tested and reasons why. If this library has unit and/or integration testing, tests should be added for new functionality and existing tests should complete without errors. 

[x] This change adds test coverage

[x] This change has been tested on the latest version of Symfony

### Checklist

[x] I have read the [Auth0 general contribution guidelines](https://github.com/auth0/open-source-template/blob/master/GENERAL-CONTRIBUTING.md)

[x] I have read the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md)

[x] All existing and new tests complete without errors

### CODE REVIEW

**Comment by darthf1** [comment]
ping @lbalmaceda @joshcanhelp

**Comment by msznaper** [comment]
@joshcanhelp

**Comment by cocojoe** [comment]
Hey @dunglas as per my comments moving chat to here from #96 unless there are concerns between the two approaches?

**Comment by Widcket** [comment]
This is now out in [3.4.0](https://packagist.org/packages/auth0/jwt-auth-bundle#3.4.0).

**Pull request merged**
