### PR TITLE
Configuration authorized_issuer string or array compatibility

### PR DESCRIPTION
**Pull request by antzo**
### Changes

Fix **BC** introduced in last PR. Now the `authorized_issuer` can really be a string or an array. I also added tests to the `Configuration`

### Testing

[x] This change adds test coverage
[x] All existing and new tests complete without errors

### CODE REVIEW

**Comment by joshcanhelp** [comment]
@antzo - Did you pull the latest before creating this PR? Looks like you've got a conflict to resolve.

**Comment by antzo** [comment]
@joshcanhelp 3.3 merged. thanks :)

**Comment by joshcanhelp** [comment]
```
~/Sites/jwt-auth-bundle antzo-master
❯ snyk test

Testing /Users/josh-cunningham/Sites/jwt-auth-bundle...

Organization:      auth0-sdks
Package manager:   composer
Target file:       composer.lock
Open source:       no
Project path:      /Users/josh-cunningham/Sites/jwt-auth-bundle
Licenses:          enabled

✓ Tested 35 dependencies for known issues, no vulnerable paths found.
```

**Comment by joshcanhelp** [comment]
Forced merge as checks are not completing for forked PRs.

**Pull request merged**
