### PR TITLE
Add composer.lock file

### PR DESCRIPTION
**Pull request by lbalmaceda**
### Changes

This PR explicitly adds the composer.lock file required for Snyk to report vulnerabilities.
Ideally this should run as part of a CI build. I'll migrate this to CircleCI soon.

### References

https://snyk.io/docs/snyk-for-php/

### Testing
You can run the check locally using the Snyk CLI.

```sh
snyk test
```

### Checklist

- [x] I have read the [Auth0 general contribution guidelines](https://github.com/auth0/open-source-template/blob/master/GENERAL-CONTRIBUTING.md)

- [x] I have read the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md)

- [ ] All existing and new tests complete without errors

### CODE REVIEW

**Comment by lbalmaceda** [comment]
@joshcanhelp Any clue on why the tests are failing? I only committed the lock file

**Comment by joshcanhelp** [comment]
@lbalmaceda - It says it ran out of memory 😬 ... I'll try re-running. There are a quite a few jobs here, I don't know if those are all necessary.

**Comment by lbalmaceda** [comment]
@joshcanhelp Let me know if I can remove some 👍

**Comment by lbalmaceda** [comment]
Closing. I'll generate the lock files on the CI build

**Pull request closed without merging**
